#allows the user to right click harvest crops
rightClickHarvest = true
#allows the user to disable salt generation in the world, default is false
disableSaltGeneration = true

#Croptopia tree generation
[worldGeneration]

	#Settings for orange_tree_configured
	[worldGeneration.orange_tree_configured]
		biomes = []

	#Settings for dragon_fruit_tree_configured
	[worldGeneration.dragon_fruit_tree_configured]
		biomes = []

	#Settings for kumquat_tree_configured
	[worldGeneration.kumquat_tree_configured]
		biomes = []

	#Settings for banana_tree_configured
	[worldGeneration.banana_tree_configured]
		biomes = []

	#Settings for plum_tree_configured
	[worldGeneration.plum_tree_configured]
		biomes = []

	#Settings for date_tree_configured
	[worldGeneration.date_tree_configured]
		biomes = []

	#Settings for cashew_tree_configured
	[worldGeneration.cashew_tree_configured]
		biomes = []

	#Settings for mango_tree_configured
	[worldGeneration.mango_tree_configured]
		biomes = []

	#Settings for coconut_tree_configured
	[worldGeneration.coconut_tree_configured]
		biomes = []

	#Settings for apricot_tree_configured
	[worldGeneration.apricot_tree_configured]
		biomes = []

	#Settings for nutmeg_tree_configured
	[worldGeneration.nutmeg_tree_configured]
		biomes = []

	#Settings for persimmon_tree_configured
	[worldGeneration.persimmon_tree_configured]
		biomes = []

	#Settings for almond_tree_configured
	[worldGeneration.almond_tree_configured]
		biomes = []

	#Settings for avocado_tree_configured
	[worldGeneration.avocado_tree_configured]
		biomes = []

	#Settings for fig_tree_configured
	[worldGeneration.fig_tree_configured]
		biomes = []

	#Settings for cinnamon_tree_configured
	[worldGeneration.cinnamon_tree_configured]
		biomes = []

	#Settings for peach_tree_configured
	[worldGeneration.peach_tree_configured]
		biomes = []

	#Settings for apple_tree_configured
	[worldGeneration.apple_tree_configured]
		biomes = []

	#Settings for pear_tree_configured
	[worldGeneration.pear_tree_configured]
		biomes = []

	#Settings for grapefruit_tree_configured
	[worldGeneration.grapefruit_tree_configured]
		biomes = []

	#Settings for star_fruit_tree_configured
	[worldGeneration.star_fruit_tree_configured]
		biomes = []

	#Settings for nectarine_tree_configured
	[worldGeneration.nectarine_tree_configured]
		biomes = []

	#Settings for lemon_tree_configured
	[worldGeneration.lemon_tree_configured]
		biomes = []

	#Settings for cherry_tree_configured
	[worldGeneration.cherry_tree_configured]
		biomes = []

	#Settings for lime_tree_configured
	[worldGeneration.lime_tree_configured]
		biomes = []

	#Settings for pecan_tree_configured
	[worldGeneration.pecan_tree_configured]
		biomes = []

	#Settings for walnut_tree_configured
	[worldGeneration.walnut_tree_configured]
		biomes = []

