# Almost copied from https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/.github/workflows/modlist.yml

name: Update Modlist

on:
    push:
        branches:
            - "develop"
            - "fix/*"
            - "feat/*"
            - "chore/*"
            - "tech/*"
        paths:
            - MODLIST.html
            - minecraftinstance.json
            - .github/workflows/modlist.yml
            - scripts/generate-manifest.js
            - scripts/generate-modlist.js

permissions:
  contents: write

jobs:
    job:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3

            - run: npm install
            - run: npm run modlist

            - name: Run git commit
              run: |
                  git config user.name "$(git log -n 1 --pretty=format:%an minecraftinstance.json)"
                  git config user.email "$(git log -n 1 --pretty=format:%ae minecraftinstance.json)"

                  git add MODLIST.html README.md manifest.json && git commit -m "Update MODLIST"
                  git push
              env:
                  GIT_COMMITTER_NAME: github-actions[bot]
                  GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
