name: Prettier

on:
  push:
    branches:
      - 'fix/*'
      - 'feat/*'
      - 'chore/*'
      - 'tech/*'
      - 'develop'

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Node.js
      - uses: actions/setup-node@v3

      # Install Prettier
      - run: npm install prettier/prettier

      # Run Prettier (it will automatically respect .prettierignore)
      - run: npx prettier --write .

      # If there are any changes needed, you can also automatically format and push
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Prettier formatting"
          git push
        continue-on-error: true
