onEvent('recipes', event => {
  setBalanceRecipes({
    shapeless: () => {},
    application: () => {},
    compacting: () => {},
    crushing: () => {},
    filling: () => {},
    mechanical_crafting: () => {
      [
        'createaddition:mechanical_crafting/electric_motor',
        'createaddition:mechanical_crafting/alternator',
        'create:mechanical_crafting/crushing_wheel',
      ].forEach(id => event.remove({id: id}));
    },
    milling: () => {
      [
        'create:compat/botania/milling/red_petal',
        'create:compat/botania/milling/orange_petal',
        'create:compat/botania/milling/yellow_petal',
        'create:compat/botania/milling/green_petal',
        'create:compat/botania/milling/lime_petal',
        'create:compat/botania/milling/blue_petal',
        'create:compat/botania/milling/light_blue_petal',
        'create:compat/botania/milling/cyan_petal',
        'create:compat/botania/milling/purple_petal',
        'create:compat/botania/milling/magenta_petal',
        'create:compat/botania/milling/pink_petal',
        'create:compat/botania/milling/brown_petal',
        'create:compat/botania/milling/black_petal',
        'create:compat/botania/milling/gray_petal',
        'create:compat/botania/milling/light_gray_petal',
        'create:compat/botania/milling/white_petal',
        'create:milling/charcoal',
        'create:compat/upgrade_aquatic/milling/flowering_rush',
        'create:milling/allium',
        'create:milling/cocoa_beans',
        'create:milling/bone',
        'create:milling/red_tulip',
        'create:milling/lily_of_the_valley',
        'create:milling/large_fern',
        'create:milling/coal',
        'create:compat/upgrade_aquatic/milling/white_searocket',
        'create:milling/beetroot',
        'create:milling/orange_tulip',
        'create:compat/upgrade_aquatic/milling/pink_searocket',
        'create:milling/sunflower',
        'create:milling/cactus',
        'create:milling/white_tulip',
        'create:milling/lilac',
        'create:milling/dandelion',
        'create:milling/wither_rose',
        'create:milling/pink_tulip',
        'create:milling/fern',
        'create:milling/peony',
        'create:milling/cornflower',
        'create:milling/azure_bluet',
        'create:milling/rose_bush',
        'create:milling/poppy',
        'create:compat/tconstruct/milling/necrotic_bone',
        'create:milling/lapis_lazuli',
        'create:milling/bone_meal',
        'create:milling/ink_sac',
        'create:milling/sea_pickle',
        'create:milling/oxeye_daisy',
        'create:milling/blue_orchid',
      ].forEach(id => event.remove({id: id}));
    },
    mixing: () => {},
    pressing: () => {},
    sequenced_assembly: () => {},
    splashing: () => {},
  });
});
